import { BookModel } from './models';

export const MOCK_BOOKS: BookModel[] = [
    {
        id: 1,
        title: 'Nhà Giả Kim',
        author: 'Paulo Coelho',
        description: 'Hành trình của cậu bé chăn cừu Santiago đi tìm kho báu và tìm thấy chính mình.',
        coverUrl: 'https://picsum.photos/seed/alchemist/400/600',
        isFavorite: true,
        chapters: [
            { title: 'Cậu bé chăn cừu', pages: 34 },
            { title: 'Vị vua già', pages: 28 },
            { title: 'Sa mạc', pages: 45 },
            { title: 'Kim tự tháp', pages: 39 },
        ],
    },
    {
        id: 2,
        title: 'Đắc Nhân Tâm',
        author: 'Dale Carnegie',
        description: 'Nghệ thuật thu phục lòng người và xây dựng các mối quan hệ bền vững.',
        coverUrl: 'https://picsum.photos/seed/carnegie/400/600',
        isFavorite: false,
        chapters: [
            { title: 'Nghệ thuật ứng xử căn bản', pages: 62 },
            { title: 'Sáu cách tạo thiện cảm', pages: 71 },
            { title: 'Thuyết phục người khác', pages: 88 },
        ],
    },
    {
        id: 3,
        title: 'Sapiens: Lược Sử Loài Người',
        author: 'Yuval Noah Harari',
        description: 'Hành trình 70.000 năm từ loài vượn tầm thường tới kẻ thống trị hành tinh.',
        coverUrl: 'https://picsum.photos/seed/sapiens/400/600',
        isFavorite: true,
        chapters: [
            { title: 'Loài vật tầm thường', pages: 52 },
            { title: 'Cây tri thức', pages: 48 },
            { title: 'Một ngày trong đời Adam và Eva', pages: 61 },
            { title: 'Đại hồng thuỷ', pages: 37 },
            { title: 'Cuộc lừa dối vĩ đại nhất', pages: 55 },
        ],
    },
    {
        id: 4,
        title: 'Clean Code',
        author: 'Robert C. Martin',
        description: 'Cẩm nang viết mã nguồn sạch sẽ, dễ đọc và dễ bảo trì cho lập trình viên.',
        coverUrl: 'https://picsum.photos/seed/cleancode/400/600',
        isFavorite: true,
        chapters: [
            { title: 'Đặt tên có ý nghĩa', pages: 24 },
            { title: 'Hàm', pages: 32 },
            { title: 'Chú thích', pages: 26 },
            { title: 'Định dạng mã nguồn', pages: 21 },
            { title: 'Xử lý lỗi', pages: 18 },
        ],
    },
    {
        id: 5,
        title: 'Tôi Thấy Hoa Vàng Trên Cỏ Xanh',
        author: 'Nguyễn Nhật Ánh',
        description: 'Tuổi thơ nghèo khó nhưng trong trẻo ở một làng quê miền Trung.',
        coverUrl: 'https://picsum.photos/seed/hoavang/400/600',
        isFavorite: false,
        chapters: [
            { title: 'Chuyện của Thiều', pages: 41 },
            { title: 'Con Mận', pages: 38 },
            { title: 'Cơn lũ', pages: 44 },
        ],
    },
    {
        id: 6,
        title: 'Dune - Xứ Cát',
        author: 'Frank Herbert',
        description: 'Cuộc chiến quyền lực trên hành tinh sa mạc Arrakis, nơi có loại gia vị quý nhất vũ trụ.',
        coverUrl: 'https://picsum.photos/seed/dune/400/600',
        isFavorite: false,
        chapters: [
            { title: 'Dune', pages: 96 },
            { title: 'Muad Dib', pages: 84 },
            { title: 'Nhà tiên tri', pages: 78 },
        ],
    },
    {
        id: 7,
        title: 'Rừng Na Uy',
        author: 'Haruki Murakami',
        description: 'Câu chuyện về tình yêu, mất mát và tuổi trẻ ở Tokyo những năm 1960.',
        coverUrl: 'https://picsum.photos/seed/norwegian/400/600',
        isFavorite: true,
        chapters: [
            { title: 'Cánh đồng cỏ', pages: 47 },
            { title: 'Naoko', pages: 53 },
            { title: 'Midori', pages: 49 },
            { title: 'Mùa đông', pages: 42 },
        ],
    },
    {
        id: 8,
        title: 'Muôn Kiếp Nhân Sinh',
        author: 'Nguyên Phong',
        description: 'Những chiêm nghiệm về luật nhân quả qua lời kể của một nhà tài chính phố Wall.',
        coverUrl: 'https://picsum.photos/seed/muonkiep/400/600',
        isFavorite: false,
        chapters: [
            { title: 'Cuộc gặp gỡ', pages: 36 },
            { title: 'Ai Cập cổ đại', pages: 58 },
            { title: 'Luật nhân quả', pages: 64 },
        ],
    },
];